debug: False
publish_hz: 10
# WorldToColor : Color camera Extrinsic Matrix, From World coordinate To Color Camera Matrix.
# This can get from Color camera calibration
WorldToColor: [-0.134,   0.989, -0.063, -600,
                0.512,   0.015, -0.859, -221,
                -0.848, -0.148, -0.508, 1760,
                0,       0,      0,      1] 

# DepthToColor : From Depth camera To Color camera transform Matrix.
# This can get from azure kinect ros driver launch.
DepthToColor: [0.999996,   0.00100766, 0.00273671, -31.9884,
              -0.0012537,  0.995809,   0.0914447,  -2.11301,
              -0.0026331, -0.0914478,  0.995806,    3.91359,
              0,           0,          0,           1]

# WorldToMap : From World coordinate To Map Coordinate transform matrix.
WorldToMap: [1, 0, 0, 0,
              0, 1, 0, 0,
              0, 0, 1, 0,
              0, 0, 0, 1]

